baseURL = "http://elben.netlify.com/"
languageCode = "en-us"
title = "My personal web page"
theme = "minimal"

[params]
    author = "Jakob Jul Elben"
    description = "Personal blog theme powered by Hugo"
    githubUsername = "elben10"
    accent = "grey"
    link_color = "blue"
    showBorder = true
    backgroundColor = "white"
    font = "Quicksand" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "xcode"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift", "r"]
    css = ["css/style.css"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:elbenjakobjul@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/elben10/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/jakobelben/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/jakobjulelben/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://www.stackoverflow.com/users/6280351/jakob-jul-elben/"
    name = "stack-overflow"
    weight = 5
